// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtvaskojvmyqoovtezmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dmFza29qdm15cW9vdnRlem10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Nzg4NjEsImV4cCI6MjA2MTE1NDg2MX0.7uWUiL__YGccsIXKA4hsqD4PWa1WTNoPPrfjz4V4s4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);